In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4108, 9823, 6737, 4008],
 [4108, 9823, 6737, 2385],
 [4108, 5756, 6737, 7396],
 [7504, 1152, 8255, 1445, 7725],
 [7504, 1152, 8255, 1445, 6539],
 [9983, 4108, 8352, 6737, 8667],
 [4818, 5046, 5614, 1445]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4108 9823 6737 4008]
 [   0    0    0    0 4108 9823 6737 2385]
 [   0    0    0    0 4108 5756 6737 7396]
 [   0    0    0 7504 1152 8255 1445 7725]
 [   0    0    0 7504 1152 8255 1445 6539]
 [   0    0    0 9983 4108 8352 6737 8667]
 [   0    0    0    0 4818 5046 5614 1445]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/Users/tanvipatel/Documents/deep_learning_project/venv-ann/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[[ 7.51476362e-03,  4.11792062e-02, -3.65641713e-02,
         -4.43692803e-02, -8.71579722e-03, -4.41621542e-02,
         -7.87776709e-03, -7.26815313e-03,  3.87090780e-02,
          2.47924812e-02],
        [ 7.51476362e-03,  4.11792062e-02, -3.65641713e-02,
         -4.43692803e-02, -8.71579722e-03, -4.41621542e-02,
         -7.87776709e-03, -7.26815313e-03,  3.87090780e-02,
          2.47924812e-02],
        [ 7.51476362e-03,  4.11792062e-02, -3.65641713e-02,
         -4.43692803e-02, -8.71579722e-03, -4.41621542e-02,
         -7.87776709e-03, -7.26815313e-03,  3.87090780e-02,
          2.47924812e-02],
        [ 7.51476362e-03,  4.11792062e-02, -3.65641713e-02,
         -4.43692803e-02, -8.71579722e-03, -4.41621542e-02,
         -7.87776709e-03, -7.26815313e-03,  3.87090780e-02,
          2.47924812e-02],
        [-3.86560671e-02,  3.60332020e-02,  3.62086929e-02,
          1.14559010e-03, -2.68219467e-02, -1.96139105e-02,
          2.12665647e-03, -3.64271998e-02,  4.478838

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 4108, 9823, 6737, 4008], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None